# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


## This yaml is for enabling automatic trigger of the pipeline when a merge requested is accepted and merged to main branch
trigger:
- main
- release-2025

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'other'
    extraProperties: 'sonar.projectKey=Feb2025-Java-Maven-Yaml-Pipeline_Feb2025-Java-Maven-Yaml-Pipeline_32e41e31-8640-4752-8e77-11899db67430'

- task: Maven@4
  inputs:
    sonarQubeRunAnalysis: true

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'