# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


## This yaml is for enabling automatic trigger of the pipeline when a merge requested is accepted and merged to main branch
trigger:
- main
- release-2025

pool:
  vmImage: ubuntu-latest

variables:
  mavenPOMFile: 'pom.xml'
steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=Feb2025-Java-Maven-CI-Using-UI-Approach_java-unit-tests-maven.git_ea6ab8e4-bee6-409b-9a11-1594bd8957e0
      sonar.projectName=java-unit-tests-maven.git

# - task: Maven@4
#   inputs:
#     sonarQubeRunAnalysis: true

- task: JavaToolInstaller@1
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: Maven@4
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '*/surefire-reports/TEST-.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'


- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'